### ISSUE TITLE
I  need some advice for AIX 7.2

### ISSUE THREAD

**Issue by camelx1** [jhrozek/pam_hbac#103]
I did everything according to the instruction(from freeipa) and it works fine.
But it works  with KRB5 and LDAP without PAM modules.

I had compiled pam_hbac for AIX and then wrote correct pam_hbac.conf
I passed the test(user -  allow, user1 - deny):
```
bash-4.3# /tmp/pam_hbac/pam_test_client user1 sshd
service: sshd
user: user1
testing pam_acct_mgmt
pam_acct_mgmt: Permission denied
bash-4.3# /tmp/pam_hbac/pam_test_client user sshd
service: sshd
user: user
testing pam_acct_mgmt
pam_acct_mgmt: Success
bash-4.3#
``` 
I added string to pam.conf: 
`sshd    account required        /usr/lib/security/pam_hbac.so ignore_unknown_user ignore_authinfo_unavail`

I  tried to mix PAM and KRB5 auth - but it still not working for me.
Maybe someone has successful experience and can share with me?

**Comment by jhrozek** [comment]
Which branch or tag did you build from? The AIX support wasn't merged yet, see PR #101

**Comment by jhrozek** [comment]
merged to master, that is

**Comment by camelx1** [comment]
I builded from AIX branch.
Today i have saw some dependency
module doesn't work with openldap-2.4.44-0.1 (which needs for lastest version "sudo")
but it works with openldap-2.4.40-2

**Comment by camelx1** [comment]
I cant understand why official site IBM provides with sudo 1.8.20 which needs openldap-2.4.44-0.1, but doesn't provide with this version openldap. And i have to download from unofficial site(perzl.org)

**Comment by camelx1** [comment]
I have found solution for first question:
I changed strings into /etc/pam.conf:```

OTHER   auth    required        pam_aix
sshd    account required        pam_hbac.so ignore_unknown_user ignore_authinfo_unavail
OTHER   account required        pam_aix
OTHER   password  required      pam_aix
OTHER   session required        pam_aix
```
Now I have problem with dependency between openldap version  2.4.40 and 2.4.44

How i can build module with other path to openldap lib  or module includes this lib?

**Comment by jhrozek** [comment]
I wonder if @johnnys66 ran into this issue?

But normally, you'd modify the CFLAGS and LDFLAGS you use during, e.g:
```
export CFLAGS="$CFLAGS -I/some/include/path"
export LDFLAGS="$LDFLAGS -L/some/lib/path"
./configure
make
...
```

btw I'm not an AIX user, so I'm not sure if the AIX compiler uses the same flags, but hopefully yes..

**Comment by jhrozek** [comment]
Hi, does setting the CFLAGS and LDFLAGS help?

**Comment by camelx1** [comment]
I have found another solution, and I wil  make and publish small tutorial "aix+sudo+freeipa+pam_hbac"  little bit later

**Comment by jhrozek** [comment]
OK, I'm really glad you fixed this.

That said, could you give me a hint if anything needs to be changed in the aix branch? If it works for you in general, I will merge it and release a new pam_hbac version upstream so that the AIX port is easier to consume by more users.

Also, please send your tutorial to freeipa-users, there are many users there who would appreciate your work.
