### ISSUE TITLE
AIX 7.1 TL5, autoreconf gives error autoreconf: automake failed with exit status: 1

### ISSUE THREAD

**Issue by grakholia** [jhrozek/pam_hbac#116]
I have installed all pre-requisite and ny server is already an IPA client.
When trying to run autoreconf -if it gives me below errors, is it OK to move forward? if NOT then what can be done to fix this?

#autoreconf -if
/opt/freeware/bin/sed: -e expression #1, char 120: unterminated `s' command
/opt/freeware/bin/sed: -e expression #1, char 132: unterminated `s' command
/opt/freeware/bin/sed: -e expression #1, char 116: unterminated `s' command
/opt/freeware/bin/sed: -e expression #1, char 134: unterminated `s' command
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
/opt/freeware/bin/sed: -e expression #1, char 138: unterminated `s' command
/opt/freeware/bin/sed: -e expression #1, char 136: unterminated `s' command
libtoolize: putting macros in 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
/opt/freeware/bin/sed: -e expression #1, char 128: unterminated `s' command
libtoolize: Remember to add 'LT_INIT' to configure.ac.
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
configure.ac:26: installing 'build/ar-lib'
configure.ac:22: installing 'build/compile'
configure.ac:19: installing 'build/config.guess'
configure.ac:19: installing 'build/config.sub'
configure.ac:21: installing 'build/install-sh'
configure.ac:30: error: required file 'build/ltmain.sh' not found
configure.ac:21: installing 'build/missing'
Makefile.am: installing 'build/depcomp'
parallel-tests: installing 'build/test-driver'
autoreconf: automake failed with exit status: 1

Thank you,

**Comment by jhrozek** [comment]
I don't have access to an AIX machine anymore to test, sorry, but I wonder if it helps to add LT_INIT or AC_CONFIG_MACRO_DIRS([m4]) to configure.ac?

**Comment by jhrozek** [comment]
No reply for almost two weeks, so I'm closing the issue.

Feel free to reopen if you think there is a bug in the autoconf script machinery.
