### ISSUE TITLE
HBAC rules do not match, because of AD group membership is sometimes missing

### ISSUE THREAD

**Issue by MatthiasLenhardt** [jhrozek/pam_hbac#119]
Hi Jakub,

at first also from me: Thanks for your great work on this pam module!

We would appreciate to use it for our Solaris 10 and 11 Systems to login there with AD users. We have allready an established trust from IdM to our AD and login with AD users on Solaris Clients is working perfect.

Now I started to configure hbac rules using the pam_hbac module on the Solaris systems ...

Unfortunately I may face an issue with the known problem, that AD group membership is sometimes not fully shown for AD users (see e.g. https://access.redhat.com/solutions/1506653). And that may be the reason, why my hbac rules sometimes do not match. The host thinks the user is not member of the group used in the hbac rule, so access is denied. I have to say "sometimes" because, as soon as the host is aware of the full AD group memberships, the hbac rule matches and login is granted.

The issue seems to be solved with higher versions of sssd, but as my legacy clients do not have sssd, I would like to ask, whether this could be the reason, why pam_hbac module sometimes denies access and if so, is there a solution for this?

Thanks in advance!

IPA version 4.5.0
pam_hbac version 1.2.1
Clients with Solaris 10 and 11
Trust between IPA and AD

Best regards
Matthias

**Comment by jhrozek** [comment]
The group list pam_hbac reads from the compat plugin is populated by sssd running on the ipa server. When the issue occurs does sssd on the ipa server report the complete group membership?

**Comment by MatthiasLenhardt** [comment]
The command `groups <ADuser>` on ipa server is showing the full group membership list, on the solaris client it doesn't (nscd is disabled on the Solaris Client).

May be it's not relevant, but after login is denied on the client, I found contrary log messages:

/var/log/authlog on Solaris Client:
Jul 18 13:23:10 uranos01536-3 sshd[16667]: [ID 596282 auth.notice] [< hbac_evaluate()
Jul 18 13:23:10 uranos01536-3 sshd[16667]: [ID 368321 auth.notice] The rule [unix-all] did not match.
Jul 18 13:23:10 uranos01536-3 sshd[16667]: [ID 559000 auth.notice] hbac_evaluate() >]

/var/log/sssd/sssd_idm.gskv.org.log on ipa server:
(Wed Jul 18 13:23:10 2018) [sssd[be[idm.gskv.org]]] [ipa_hbac_evaluate_rules] (0x0080): Access granted by HBAC rule [unix-all]

The messages should show the same login request, because AD user login is still very rare used here.

**Comment by jhrozek** [comment]
OK, then we need to find out why are the groups not propagated correctly to the compat tree. Did you say the error only happens sometimes and sometimes it works? There was a race condition in sssd we fixed some time ago, this might be similar..

**Comment by MatthiasLenhardt** [comment]
I'm running on a quite current version of sssd on the ipa servers: 1.16.0-19.el7_5.5

And you think, it's not the issue, that if "another" as the user itself is asking AD (over IdM/sssd) for groupmembership, e.g. the LDAP bind user, that than not the full list of groups will be returned from the AD? This "exchange of MS-PAC information" issue in  https://access.redhat.com/solutions/1506653?

**Comment by jhrozek** [comment]
The recent version is still not enough because the fix was not released yet :-) It's https://pagure.io/SSSD/sssd/issue/3744 which was only fixed upstream, but not in RHEL yet.

I don't think the PAC issue is the same, because unless you log in to the IDM servers with the same user using kerberos, the PAC doesn't come to play.

**Comment by MatthiasLenhardt** [comment]
Would be great! Do you think, it's worth opening a support request at Red Hat?

**Comment by jhrozek** [comment]
Red hat won’t support Pam-hbac but I can build you a test package

**Comment by MatthiasLenhardt** [comment]
Not for pam_hbac, but sssd?
But don't stress yourself - You allready helped enough! I'm having a look at the 1.16.2 version of sssd and will install it on our test envrironment. Maybe it takes not too long until the new version is released by Red Hat.
I'm now more confident, that the solution is not far away! :-)

**Comment by MatthiasLenhardt** [comment]
It seems, the 1.16.2 version solves this. I opened a Red Hat Support Call (https://access.redhat.com/support/cases/#/case/02176081) and Red Hat provided me a test package. With this I can see the full groupmembership of my AD users, so the hbac rules are matching.

I would like to continue testing, but I'm confident ...

**Comment by MatthiasLenhardt** [comment]
Now I'm quite sure, we can close this issue.

I tested with RHEL 7.6, which includes sssd 1.16.2(-13.el7) and now the full group membership is shown.

Thanks!
