### ISSUE TITLE
autoreconf fails on OSX

### ISSUE THREAD

**Issue by jhrozek** [jhrozek/pam_hbac#50]
``` shell
external/libunistring.m4:1: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
src/build_macros.m4:15: PH_AC_EXPAND_LIB_DIR is expanded from...
external/libunistring.m4:1: the top level
external/libunistring.m4:1: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
src/build_macros.m4:15: PH_AC_EXPAND_LIB_DIR is expanded from...
external/libunistring.m4:1: the top level
external/libunistring.m4:1: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
src/build_macros.m4:15: PH_AC_EXPAND_LIB_DIR is expanded from...
external/libunistring.m4:1: the top level
configure:12521: error: possibly undefined macro: AC_LIB_PREPARE_PREFIX
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:12524: error: possibly undefined macro: AC_LIB_WITH_FINAL_PREFIX
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
```

I do have libtool and gettext installed and I'm not sure where should the AC_LIB_WITH_FINAL_PREFIX come from..

**Comment by jhrozek** [comment]
CC @lslebodn because I stole the libunistring from SSSD where he Lukas wrote it :-)

**Comment by lslebodn** [comment]
On (27/03/16 04:23), Jakub Hrozek wrote:

> CC @lslebodn because I stole the libunistring from SSSD where he Lukas wrote it :-)
> 
> Macros AC_LIB_PREPARE_PREFIX and AC_LIB_WITH_FINAL_PREFIX are defined in
> the file /usr/share/aclocal/lib-prefix.m4 on fedora.

They are part of package gettext-devel
sh$ rpm -qf /usr/share/aclocal/lib-prefix.m4
gettext-devel-0.19.7-4.fc24.x86_64

Macro in file src/build_macros.m4 simplify
build on platforms where libraries are not installed in standard paths.
e.g. /usr/local/ ...

There are few solutions:
- Use pkg-config for detectin of libunistring.
  (there isn't pkgconfig file on fedora but might be on MAC OS)
- remove expansion of libdir at configure time (remove usage of macro
  PH_AC_EXPAND_LIB_DIR).
- Use macro AC_LIB_PREPARE_PREFIX in PH_AC_EXPAND_LIB_DIR only if it is
  available.
- install missing files (gettext) if available

LS

**Comment by lslebodn** [comment]
On (30/03/16 14:09), lslebodn wrote:

> On (27/03/16 04:23), Jakub Hrozek wrote:
> 
> > CC @lslebodn because I stole the libunistring from SSSD where he Lukas wrote it :-)
> > 
> > Macros AC_LIB_PREPARE_PREFIX and AC_LIB_WITH_FINAL_PREFIX are defined in
> > the file /usr/share/aclocal/lib-prefix.m4 on fedora.
> 
> They are part of package gettext-devel
> sh$ rpm -qf /usr/share/aclocal/lib-prefix.m4
> gettext-devel-0.19.7-4.fc24.x86_64
> 
> Macro in file src/build_macros.m4 simplify
> build on platforms where libraries are not installed in standard paths.
> e.g. /usr/local/ ...
> 
> There are few solutions:
> - Use pkg-config for detectin of libunistring.
>   (there isn't pkgconfig file on fedora but might be on MAC OS)
> - remove expansion of libdir at configure time (remove usage of macro
>   PH_AC_EXPAND_LIB_DIR).
> - Use macro AC_LIB_PREPARE_PREFIX in PH_AC_EXPAND_LIB_DIR only if it is
>   available.
> - install missing files (gettext) if available
> 
> Bump,

have you already decided which way would you like to choose?

LS

**Comment by jhrozek** [comment]
I haven't so far because I don't plan to support OS X in the first version only Linux BSD and Solaris

**Comment by jhrozek** [comment]
Fixed
