### ISSUE TITLE
module ignored when host does not exist in IPA and allowing login - solaris 10

### ISSUE THREAD

**Issue by johnnys66** [jhrozek/pam_hbac#91]
First of all, thanks a lot for this module!  We can now fully expand IPA to legacy clients and other platforms.

Not sure if this is a bug or a misuse but if the client hostname doesn't exist in IPA the module gets ignored and login is allowed instead of denied.
Module compiled in solaris 10 64bit, using the build tools from opencsw. Followed README.Solaris.

log messages:
Sep  5 14:22:37 SODDUNIX001 sshd[10384]: [ID 621728 auth.debug] Searching for host SODDUNIX001 using filter [fqdn=SODDUNIX001]
Sep  5 14:22:37 SODDUNIX001 sshd[10384]: [ID 544684 auth.debug] Searching LDAP using filter [(&(objectclass=ipaHost)(fqdn=SODDUNIX001))] base [cn=computers,cn=accounts,dc=ipa,dc=mngt,dc=local] timeout [5]
Sep  5 14:22:37 SODDUNIX001 sshd[10384]: [ID 237654 auth.debug] Found 0 entries
Sep  5 14:22:37 SODDUNIX001 sshd[10384]: [ID 678097 auth.warning] No such host SODDUNIX001
Sep  5 14:22:37 SODDUNIX001 sshd[10384]: [ID 965217 auth.notice] Did not find host SODDUNIX001 denying access
Sep  5 14:22:37 SODDUNIX001 sshd[10384]: [ID 623785 auth.debug] returning [25]: Ignore module

If the host exists the module works perfectly, allowing or denying access depending on the hbac rules.

By the way, you have a typo in pam_hbac_compat.h:
where you have
# define strndp portable_strndup

it should be
# define strndup portable_strndup

Once more, thanks!

**Comment by jhrozek** [comment]
The hostname pam_hbac searches for is by default the machine hostname, if you want to override that with a custom hostname you can set HOST_NAME in pam_hbac.conf, does that help?

**Comment by jhrozek** [comment]
btw the typo was just fixed in 5632843b00cc096eefc03fb67dc355c09017b7f0, thanks for reporting that

**Comment by johnnys66** [comment]
The issue here, in my opinion, is not the override of the hostname. The problem is that if the host is not defined in IPA, login access should be denied by default. Otherwise in case you forget, for whatever reason, to register the host in IPA, any user will be allowed to login, despite all the habc rules that might exist.

**Comment by jhrozek** [comment]
ok, right. The last two messages say:
Sep 5 14:22:37 SODDUNIX001 sshd[10384]: [ID 965217 auth.notice] Did not find host SODDUNIX001 denying access
Sep 5 14:22:37 SODDUNIX001 sshd[10384]: [ID 623785 auth.debug] returning [25]: Ignore module

so we're converting a deny to ignore, would you mind pasting how is the pam_hbac module configured in the PAM stack? Do you use either of ignore_authinfo_unavail or ignore_unknown_user? Does the 'ignored' result turn into denial if you remove these options?

**Comment by johnnys66** [comment]
other   account required      pam_ldap.so.1 debug
other   account required      pam_hbac.so debug ignore_unknown_user ignore_authinfo_unavail

Yes, by removing ignore_authinfo_unavail, if the host doesn't exist access is denied.

Although I think that a host not found in IPA shouldn't be treated the same way as the ldap server being unavailable. Nevertheless it does the trick.

**Comment by jhrozek** [comment]
I agree it's a bug. I'll see what is the right way to fix this, I suspect it would be best to not return AUTHINFO_UNAVAIL if the host search returns successfuly but doesn't find the host.

**Comment by johnnys66** [comment]
Thanks!
If you need me to run any tests I'm available.

**Comment by jhrozek** [comment]
If you can build the module from a git checkout, there is a proposed patch in the misc branch

**Comment by johnnys66** [comment]
Seems to be working. Just tested the host not found functionality:
Sep  5 16:30:22 SODDUNIX001 sshd[16223]: [ID 621728 auth.debug] Searching for host SODDUNIX001 using filter [fqdn=SODDUNIX001]
Sep  5 16:30:22 SODDUNIX001 sshd[16223]: [ID 544684 auth.debug] Searching LDAP using filter [(&(objectclass=ipaHost)(fqdn=SODDUNIX001))] base [cn=computers,cn=accounts,dc=ipa,dc=mngt,dc=local] timeout [5]
Sep  5 16:30:22 SODDUNIX001 sshd[16223]: [ID 237654 auth.debug] Found 0 entries
Sep  5 16:30:22 SODDUNIX001 sshd[16223]: [ID 678097 auth.warning] No such host SODDUNIX001
Sep  5 16:30:22 SODDUNIX001 sshd[16223]: [ID 965217 auth.notice] Did not find host SODDUNIX001 denying access
Sep  5 16:30:22 SODDUNIX001 sshd[16223]: [ID 623785 auth.debug] returning [7]: Permission denied

Using both ignore_unknown_user and ignore_authinfo_unavail module options.

**Comment by jhrozek** [comment]
Thank you for testing. To be honest, I no longer remember why we also added the ignore functionality to host searches as well. The patch just removes that code and keeps the ignore functionality for the initial connect() only (which I still think makes sense in case the IPA server went offline).

I'll push the patch to master and probably do a 1.1 release soon with the two fixes (strndup typo and the ignore removal).

**Comment by jhrozek** [comment]
fixed in dcf11d4b238585f6d563b3144e5e508875c96936
