### ISSUE TITLE
pam_hbac for Oracle VM server release 3.3.3

### ISSUE THREAD

**Issue by etc-fstab** [jhrozek/pam_hbac#96]
Hi, first of all, thanks for the tool. 
Out IPA server is 4.4. Since we have some clients that can't run ipa-client, we are using this tool. For example, I have it working on Oracle Linux 5.8 (kernel 2.6.32-300.21.1.el5uek) with installed rpm pam_hbac-1.1-1.el5.centos. 
Interestingly I am not successful (basically same configuration setup as for OL5.8) using  pam_hbac-1.1-1.el6.x86_64 on OVS 3.3.3 (which runs kernel 3.8.13-68.3.3.el6uek.x86_64).

**Comment by jhrozek** [comment]
What exactly failed? Compilation or usage?

**Comment by etc-fstab** [comment]
I believe it's usage, here is relevant pam debug logs:

sshd: pam_hbac(sshd:account): Searching for host xen-admin using filter [fqdn=xen-admin]
sshd: pam_hbac(sshd:account): Searching LDAP using filter [(&(objectclass=ipaHost)(fqdn=xen-admin))] base [cn=computers,cn=accounts,dc=us,dc=xxx,dc=com] timeout [5]
sshd: pam_hbac(sshd:account): Found 0 entries
sshd: pam_hbac(sshd:account): No such host xen-admin
sshd: pam_hbac(sshd:account): Did not find host xen-admin denying access
sshd: pam_hbac(sshd:account): returning [6]: Permission denied

The host exists in the IPA, for example the command "ipa hbactest --user=zdudic --host=xen-admin --service=ssh" shows expected output.

**Comment by jhrozek** [comment]
OK, but I would like to ask you to run another test. I think you are using a bind user and a bind password (parameters BIND_DN/BIND_PW) in the pam_hbac config file.

Could you run a similar search from the command line, using the same bind user and password? Are these parameters the same on the machines where pam_hbac works and where it doesn't?

Something like:
```
ldapsearch -H ldap://your.ipa.server -D $value_of_bind_dn -w $value_of_bind_pw -b n=computers,cn=accounts,dc=us,dc=xxx,dc=com "(&(objectclass=ipaHost)(fqdn=xen-admin))"
```

Also, looking into the DS access log on the IDM master might show why is pam_hbac not finding it.

**Comment by etc-fstab** [comment]
Thanks, the problem was that hostname was for example xen-admin (returned by command "hostname"), so just running command "hostname xen-admin.domain" makes pam_hbac working as expected. And ldapsearch command fails with "fqdn=xen-admin" but is successful with fqdn=xen-admin.domain"

**Comment by jhrozek** [comment]
Ah, we should at least warn against an unqualified hostname. I opened issue #98 to track that.
